model_params:
  name: "VQVAE"
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  beta: 0.25

data_params:
  dataset: "celeba"
  data_path: "./data/celeba"  
  train_batch_size: 64
  val_batch_size: 64
  image_size: 64
  num_workers: 4

exp_params:
  LR: 0.0003
  weight_decay: 0.0
  manual_seed: 1265

trainer_params:
  max_epochs: 50
  gpus: [0]

logging_params:
  save_dir: "logs/"
  name: "VQVAE"