model_params:
  model_name: "VanillaVAE"
  in_channels: 3
  latent_dim: 32

data_params:
  data_path: "./data/celeba"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4

exp_params:
  lr: 0.0003
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 1.0       
  manual_seed: 1265

trainer_params:
  max_epochs: 50
  log_interval: 50
